### ISSUE TITLE
Tcp socket read, without read_with

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/ublox-cellular-rs#17]
Currently this crate implements a slightly modified version of the `TcpStack` trait from [embedded-nal](https://github.com/thejpster/embedded-nal), with the addition of 

```rust
fn read_with<F>(&self, socket: &mut Self::TcpSocket, f: F) -> nb::Result<usize, Self::Error>
    where
        F: FnOnce(&[u8], Option<&[u8]>) -> usize;
```

As this allows peeking into the buffer, to selectively do copy, only if a full valid packet is in place (eg an mqtt packet).

We need to figure out a way to either commit the `read_with` fn upstream, if deemed useful, or use the regular buffered `read` without introducing additional clones

**NOTE** 
This is the blocking issue for releasing to crates.io, as git dependencies are not allowed on crates.io

**Comment by keisrk** [comment]
Came from [this](https://github.com/BlackbirdHQ/ublox-cellular-rs/pull/27). As [mentioned earlier](https://github.com/rust-embedded-community/embedded-nal/issues/12#issuecomment-736622506), we don't want to _divide the ecosystem_.
Still, can we have a polyfill `trait ClosureBasedZeroCopy: TcpClient { fn read_with(..) .. }` for the time being? It's just a temporary workaround.

**Comment by MathiasKoch** [comment]
Yep, i think that would be a great temp solution :+1: 

I will add it in mqttrust, where the `read_with` is required

**Comment by MathiasKoch** [comment]
Hmm.. nope, should probably be added somewhere else? Maybe ublox-cellular? or a completely new repo of temporary extension traits for our device?

**Comment by keisrk** [comment]
Or maybe we can simply update your `factbird-1.0` branch basing on `v0.2.0`. I just made a [PR](https://github.com/MathiasKoch/embedded-nal/pull/2). I can explore the both approaches:)

**Comment by keisrk** [comment]
Hi @MathiasKoch , perhaps we can work around the zero-copy part of discussion. I made another [PR](https://github.com/BlackbirdHQ/mqttrust/pull/17), so if you have a spare time, can you quickly have a look?
