### ISSUE TITLE
Replace Vec<..> with BBQueue in RingBuffer

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/ublox-cellular-rs#20]
In order to better support embedded-nal zero-copy API's we need to switch from using a standard ring-buffer implementation as socket buffer storage, to using a bip-style buffer allowing access to contiguous memory.

I would suggest changing to https://github.com/jamesmunns/bbqueue, while refactoring and cleaning up the ring-buffer implementation and API.

This should go hand-in-hand with the fix to https://github.com/rust-embedded-community/embedded-nal/issues/12

Also this will open up a fix to #17

**Comment by MathiasKoch** [comment]
**Update**
> That makes sense! Perhaps i should look into replacing my socket buffer implementation with a bip based version.. Perhaps based on bbqueue

It seems like bbqueue would not actually solve my issue here? It would give me a contiguous piece of memory for writing, but does not set such guarantees when reading?

**Comment by MathiasKoch** [comment]
**UPDATE**
This PR might fix the reading part: https://github.com/jamesmunns/bbqueue/pull/77

**Comment by jamesmunns** [comment]
Just as a note, bbqueue always gives you contiguous memory (for both reads and writes), though in the case of reads, you might have a "wrap" partway through the read, which can be retrieved by doing another `read()` after you have consumed the data before the wrap.

For example, if your ring had the following valid data in it:

```
                           read_ptr
                              |
                              v
| 4 | 5 | 6 | x | x | x | x | 1 | 2 | 3 |
```

Your first grant would be a contiguous slice containing `&[1, 2, 3]`, and your second grant (after releasing the first) would be `&[4, 5, 6]`.

https://github.com/jamesmunns/bbqueue/pull/77 addresses this by giving you TWO slices at the same time, essentially you get `(&[1, 2, 3], &[4, 5, 6])` at the same time.

**Comment by MathiasKoch** [comment]
@jamesmunns Thanks for reaching out!

I know that I will always get contiguous memory in both cases, but in my particular use case I am using this with an MQTT client ontop, where i do not want to dequeue anything from my queue, unless i can guarantee that I have received a full MQTT packet. In this case i need https://github.com/jamesmunns/bbqueue/pull/77 to handle wrapovers correctly (or some other workaround with some intermediate buffer)

Currently i am doing something similar with my `heapless::Vec` based buffer here: https://github.com/BlackbirdHQ/ublox-cellular-rs/blob/271022e67c3ffc63478d559bd28ab9290e4dd445/ublox-cellular/src/socket/ring_buffer.rs#L264-L288 but would like to replace that entire buffer with `bbqueue`

**Comment by MathiasKoch** [comment]
Closing in favor of https://github.com/BlackbirdHQ/ublox-sockets/issues/1
