### ISSUE TITLE
Forced `embedded-hal` dependency version

### ISSUE THREAD

**Issue by MikiLoz92** [BlackbirdHQ/ublox-cellular-rs#97]
Currently the `embedded-hal` dependency is "hardcoded" at version `=1.0.0-rc.1`. I don't know if this is a conscious decision (nor why, if it is), but if it isn't, putting a `^1.0.0-rc.1` instead would help applications consuming the `ublox-cellular-rs` crate, as, for example, there are some crates like `esp-idf-hal` that already depend on `embedded-hal` and restrict its version to possibly another one. This ends up causing version conflicts:

```
error: failed to select a version for `embedded-hal`.
    ... required by package `atat v0.13.0`
    ... which satisfies dependency `atat = "^0.13.0"` of package `ublox-cellular-rs v0.4.0`
    ... which satisfies dependency `ublox-cellular-rs = "^0.4.0"` of package `main-board v0.1.0`
versions that meet the requirements `=1.0.0-alpha.4` are: 1.0.0-alpha.4

all possible versions conflict with previously selected packages.

  previously selected package `embedded-hal v1.0.0-rc.1`
    ... which satisfies dependency `embedded-hal = "=1.0.0-rc.1"` of package `esp-idf-hal v0.42.5`
    ... which satisfies dependency `esp-idf-hal = "^0.42.5"` of package `main-board v0.1.0`

failed to select a version for `embedded-hal` which could resolve this conflict
```

**Comment by MathiasKoch** [comment]
I am not sure how cargo handles `rc.x` versions. The issue is that changing rc.1 to rc.2 might contain breaking changes, as opposed to a patch bump?

**Comment by MikiLoz92** [comment]
I understand. I'm not sure cargo handles them well, either. In any case, I think it would be good if, after `embedded-hal` makes it to `1.0.0`, this version requirement is relaxed (`^1.0.0`).

Closing this!

**Comment by MathiasKoch** [comment]
That is absolutely what i am hoping will happen soon :+1:
